### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by IBPX** [BeayemX/GitViper#2]
This project doesn't seem to have a license. [choosealicense.com](https://choosealicense.com) explains some of your choices:

- [MIT](https://choosealicense.com/licenses/mit/) lets people do whatever they want as long as they give you credit.
- [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) does that, but also includes a grant to whatever patents you might have covering the software.
- [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) lets people do most anything, but it requires that they share the source code for changes they distribute (with MIT/Apache, someone can take the source, modify it, and give that away as closed-source).

Any of those would be a good choice, depending on what your goals are.

**Comment by BeayemX** [comment]
It's the MIT license. I added the file.

Thanks
